version: '3.9'

services:
   postgres:
    image: postgres:latest
    container_name: flask-db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - Heepoke

networks:
  Heepoke:
    driver: bridge