class ResponseMessages:
    TOKEN_EXPIRED = "Token has expired"
    TOKEN_INVALID = "Invalid token"
    TOKEN_MESSING = "Token is missing"
    AUTH_LOGIN_FAILED = " Auth login failed"
    AUTH_PASSWORD_INCORRECT = "Auth password incorrect"
    AUTH_LOGOUT_SUCCESS = "Auth logout successfully"
    AUTH_LOGOUT_FAILED = "Auth logout failed"
    USER_LIST_SUCCESS = "User list successfully"
    USER_GET_BY_ID_SUCCESS = "User getBy id successfully"
    USER_GET_BY_EMAIL_USERNAME_SUCCESS = "User getBy email or username successfully"
    USER_CREATE_SUCCESS = "User created successfully"
    USER_UPDATE_SUCCESS = "User updated successfully"
    USER_DELETED_SUCCESS = "User deleted successfully"
    USER_NOT_FOUND = "User not found"
    USER_GET_BY_ID_FAILED ="User getBy id failed"